### ISSUE TITLE
Url in Readme broken?

### ISSUE THREAD

**Issue by navidcy** [JuliaGPU/buildkite#6]
https://buildkite.com/organizations/julialang/repository-providers/new seems broken?

<img width="848" alt="Screen Shot 2020-11-23 at 5 51 23 am" src="https://user-images.githubusercontent.com/7112768/99914230-0cc80200-2d50-11eb-90e7-1fdf18cefa0e.png">

**Comment by maleadt** [comment]
> ... a Buildkite administrator needs to request installation of the app ...

You're not a Buildkite admin :-)

**Comment by navidcy** [comment]
sorry..

**Comment by maleadt** [comment]
No problem, the set-up and instructions are pretty new, so it'll take a while to get them user friendly enough. If you think they can improve, feel free to create an issue or PR with suggestions!

**Comment by navidcy** [comment]
How can the user reach the Buildkite admins? Perhaps a remark on that would be helpful. (Personally I don't know myself.)

I might add something in a PR when I figure out...

**Comment by maleadt** [comment]
> Some of the steps below require administrative privileges on the JuliaLang Buildkite instance, so you should coordinate on e.g. the JuliaGPU Slack channel or Discourse category.

So it's specifically a user with adminstrative permissions on the JuliaLang Buildkite instance, like me or Valentin.
